//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace football13.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class MnfResultsView
    {
        public int MnfPointsId { get; set; }
        public string UserName { get; set; }
        public int GameId { get; set; }
        public Nullable<int> ScoreGuess { get; set; }
        public int Week { get; set; }
        public Nullable<int> Distance { get; set; }
        public Nullable<int> WinningDistance { get; set; }
    }
}
