//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace football13.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ResultsView
    {
        public int Id { get; set; }
        public int Week { get; set; }
        public string UserName { get; set; }
        public string PickTeam { get; set; }
        public Nullable<int> Points { get; set; }
        public Nullable<double> Spread { get; set; }
        public Nullable<int> HomeScore { get; set; }
        public Nullable<int> AwayScore { get; set; }
        public string HomeTeam { get; set; }
        public string AwayTeam { get; set; }
        public string FavoriteTeam { get; set; }
    }
}
