//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace football13.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Team
    {
        public Team()
        {
            this.Games = new HashSet<Game>();
            this.Games1 = new HashSet<Game>();
            this.Picks = new HashSet<Pick>();
        }
    
        public int Id { get; set; }
        public string City { get; set; }
        public string Mascot { get; set; }
        public string Image { get; set; }
        public string Abbrev { get; set; }
    
        public virtual ICollection<Game> Games { get; set; }
        public virtual ICollection<Game> Games1 { get; set; }
        public virtual ICollection<Pick> Picks { get; set; }
    }
}
